# Generated from racc-1.4.7.gem by gem2rpm5 -*- rpm-spec -*-
%define	rbname	racc

Summary:	Racc is a LALR(1) parser generator
Name:		rubygem-%{rbname}

Version:	1.4.7
Release:	2
Group:		Development/Ruby
License:	GPLv2+ or Ruby
URL:		http://i.loveruby.net/en/projects/racc/
Source0:	http://gems.rubyforge.org/gems/%{rbname}-%{version}.gem
BuildRequires:	rubygems 
BuildRequires:	ruby-devel

%description
Racc is a LALR(1) parser generator.
It is written in Ruby itself, and generates Ruby program.
NOTE: Ruby 1.8.x comes with Racc runtime module.  You
can run your parsers generated by racc 1.4.x out of the
box.

%package	doc
Summary:	Documentation for %{name}
Group:		Books/Computer books
Requires:	%{name} = %{EVRD}
BuildArch:	noarch

%description	doc
Documents, RDoc & RI documentation for %{name}.

%prep
%setup -q

%build
%gem_build

%install
%gem_install

%files
%{_bindir}/racc
%{_bindir}/racc2y
%{_bindir}/y2racc
%dir %{ruby_gemdir}/gems/%{rbname}-%{version}
%dir %{ruby_gemdir}/gems/%{rbname}-%{version}/bin
%{ruby_gemdir}/gems/%{rbname}-%{version}/bin/racc
%{ruby_gemdir}/gems/%{rbname}-%{version}/bin/racc2y
%{ruby_gemdir}/gems/%{rbname}-%{version}/bin/y2racc
%dir %{ruby_gemdir}/gems/%{rbname}-%{version}/lib
%{ruby_gemdir}/gems/%{rbname}-%{version}/lib/*.rb
%dir %{ruby_gemdir}/gems/%{rbname}-%{version}/lib/racc
%{ruby_gemdir}/gems/%{rbname}-%{version}/lib/racc/*.rb
%{ruby_gemdir}/gems/%{rbname}-%{version}/lib/racc/pre-setup
%{ruby_gemdir}/specifications/%{rbname}-%{version}.gemspec
%{ruby_sitearchdir}/%{rbname}/*.so


%files doc
%doc %{ruby_gemdir}/gems/%{rbname}-%{version}/*.rdoc
%doc %{ruby_gemdir}/gems/%{rbname}-%{version}/*.txt
%doc %{ruby_gemdir}/doc/%{rbname}-%{version}


%changelog
* Wed Feb 15 2012 Per Øyvind Karlsen <peroyvind@mandriva.org> 1.4.7-2
+ Revision: 774439
- remove dependency on rubygem(rake), it's now provided by ruby
- mass rebuild of ruby packages against ruby 1.9.1

* Fri Jan 27 2012 Alexander Khrukin <akhrukin@mandriva.org> 1.4.7-1
+ Revision: 769362
- version update 1.4.7

* Thu Nov 04 2010 Rémy Clouard <shikamaru@mandriva.org> 1.4.6-2mdv2011.0
+ Revision: 593505
- import rubygem-racc

