
%define	rbname	racc

Summary:	Racc is a LALR(1) parser generator
Name:		rubygem-%{rbname}

Version:	1.4.12
Release:	1
Group:		Development/Ruby
License:	GPLv2+ or Ruby
URL:		http://i.loveruby.net/en/projects/racc/
Source0:	http://gems.rubyforge.org/gems/%{rbname}-%{version}.gem
BuildRequires:	rubygems 
BuildRequires:	ruby-devel

%description
Racc is a LALR(1) parser generator.
It is written in Ruby itself, and generates Ruby program.
NOTE: Ruby 1.8.x comes with Racc runtime module.  You
can run your parsers generated by racc 1.4.x out of the
box.

%files
%{_bindir}/racc
%{_bindir}/racc2y
%{_bindir}/y2racc
%{gem_dir}/gems/%{rbname}-%{version}/bin/racc
%{gem_dir}/gems/%{rbname}-%{version}/bin/racc2y
%{gem_dir}/gems/%{rbname}-%{version}/bin/y2racc
%{gem_dir}/gems/%{rbname}-%{version}/lib/*.rb
%{gem_dir}/gems/%{rbname}-%{version}/lib/racc/*.rb
%{gem_dir}/gems/%{rbname}-%{version}/lib/racc/pre-setup
%{gem_dir}/specifications/%{rbname}-%{version}.gemspec
%{ruby_sitearchdir}/%{rbname}/*.so
#---------------------------------------------------------

%package	doc
Summary:	Documentation for %{name}
Group:		Books/Computer books
Requires:	%{name} = %{EVRD}
BuildArch:	noarch

%description	doc
Documents, RDoc & RI documentation for %{name}.

%files doc
%doc %{gem_dir}/gems/%{rbname}-%{version}/*.rdoc
%doc %{gem_dir}/gems/%{rbname}-%{version}/*.txt
%doc %{gem_dir}/doc/%{rbname}-%{version}
%doc %{gem_dir}/gems/%{rbname}-%{version}/rdoc/en/*.rdoc
%doc %{gem_dir}/gems/%{rbname}-%{version}/rdoc/ja/*.ja.rdoc
#---------------------------------------------------------

%prep
%setup -q

%build
%gem_build

%install
%gem_install

perl -pi -e "s|/usr/local/bin/ruby|/usr/bin/ruby|" %{buildroot}%{gem_dir}/gems/%{rbname}-%{version}/bin/racc2y
perl -pi -e "s|/usr/local/bin/ruby|/usr/bin/ruby|" %{buildroot}%{gem_dir}/gems/%{rbname}-%{version}/bin/y2racc






